set(__QT_DEPLOY_TARGET_Bluetooth_Custom_HID_FILE C:/programming/Unversity-ComputerScience/Python/Bluetooth-KeyBoard/build-Bluetooth_Custom_HID-Desktop_Qt_6_7_0_MinGW_64_bit-Debug/Bluetooth_Custom_HID.exe)
set(__QT_DEPLOY_TARGET_Bluetooth_Custom_HID_RUNTIME_DLLS C:/programming/QT_InstallationFiles/6.7.0/mingw_64/bin/Qt6Core.dll)
